name: network_tools
description: Networking Tools library which can help you discover open ports, devices on subnet and many other things. 
version: 4.0.1
issue_tracker: https://github.com/osociety/network_tools/issues
repository: https://github.com/osociety/network_tools

environment:
  sdk: ">=2.17.6 <4.0.0"

topics:
  - network
  - ping
  - arp
  - port
  - scanner

funding:
  - https://liberapay.com/OpenSociety/donate
  - https://ko-fi.com/fs0c13ty
  
dependencies:
  # A dart csv to list converter.
  csv: ^5.0.2
  # Multi-platform network ping utility.
  dart_ping: ^9.0.0
  # Defines the annotations used by json_serializable 
  get_it: ^7.6.0
  # A composable, Future-based library for making HTTP requests.
  http: ^1.1.0
  # Injectable is a convenient code generator for get_it. 
  injectable: ^2.2.0
  # Defines the annotations used by json_serializable.
  json_annotation: ^4.8.1
  # Debugging and error logging.
  logging: ^1.2.0
  # Performing mDNS queries (e.g. Bonjour, Avahi).
  multicast_dns: ^0.3.2+2
  # A comprehensive, cross-platform path manipulation library for Dart.
  path: ^1.8.3
  # Process run helpers
  process_run: ^0.13.1
  # Yet another NoSQL persistent store database solution for single process io apps.
  sembast: ^3.5.0+1
  # Cross-platform 'dart:io' that works in all platforms.
  universal_io: ^2.0.4
  

dev_dependencies:
  # Standalone generator and watcher for Dart 
  build_runner: ^2.4.6
  # A generator for injectable library.
  injectable_generator: ^2.4.0
  # Provides Dart Build System builders for handling JSON.
  json_serializable: ^6.7.1
  # Set of lint rules for Dart.
  lint: ^2.1.2
  # Writing and running Dart tests.
  test: ^1.24.6